name: crwc
version: 0.0.0

ghc-options: >-
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MonoLocalBinds
  - MultiParamTypeClasses
  - OverloadedStrings
  - ParallelListComp
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies

dependencies:
  - base == 4.9.1.0
  - bytestring == 0.10.8.1
  - deriving-compat == 0.3.6
  - free == 4.12.4
  - parsec == 3.1.11
  - recursion-schemes == 5.0.2
  - text == 1.2.2.2
  - transformers == 0.5.2.0

library:
  source-dirs: src

executables:
  crwc:
    source-dirs: app
    main: CRWC.hs
    dependencies:
      - crwc

tests:
  unit:
    source-dirs: unit
    main: Spec.hs
    dependencies:
      - crwc
      - hspec == 2.4.4
